### PR TITLE
Fix #1: limit indir to files ending with .asciidoc, .adoc, .ad, .asc or .txt

### LINKED ISSUE #1: Non-asciidoc imports affected?
https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/include-directive.adoc describes how to include code in your files, e.g. using
```
[source,java]
----
include::{sourcedir}/org/asciidoctor/Asciidoctor.java[]
----
```

But if I do that in a project that uses `indir_ext`, I get
```
:indir: /some/path/to/the/code
```
in the listing. That’s of course horrible!

According to https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/include-directive.adoc#asciidoc-vs-non-asciidoc-files asciidoc only treats files ending in .asciidoc, .adoc, .ad, .asc, or .txt as Asciidoc; presumably this extension should do the same.

### PR DESCRIPTION
**Pull request by david0**
As suggested in the issue

### CODE REVIEW

**Comment by david0** [comment]
@johannesjh: any chance for getting this merged?

**Comment by johannesjh** [comment]
thank you for the pull request and the reminder!

I am currently short on time... have you tested the change? (then I would blindly merge if that helps)

**Comment by david0** [comment]
Yes, I tested it by including an adoc file and an c file. 

Before:
grafik

after (as expected):
grafik

**Comment by johannesjh** [comment]
thank you, I created a new release to make it easier for you to use this version of asciidoctor-indir_ext

**Comment by david0** [comment]
Thank you, sorry for the failing testcase!

**Comment by johannesjh** [comment]
no problem, the failing testcase had nothing to do with your change.... the project only contained a dummy testcase.
it would be nice to add automated tests, though

**Pull request merged**
